# Generated by Django 4.0.2 on 2022-04-18 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shop_created',
        ),
        migrations.CreateModel(
            name='IsShopOrNot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_created', models.BooleanField(default=False)),
                ('shopprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.shopprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
