# Generated by Django 4.0.2 on 2022-04-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_shop_created_isshopornot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='udp',
            field=models.ImageField(default='udpdefault.jpg', upload_to='udp_pics'),
        ),
    ]
