# Generated by Django 4.0.2 on 2022-04-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_address_user_phone_number_user_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
