# Generated by Django 4.0.2 on 2022-04-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopiteam',
            name='iteam_image',
            field=models.ImageField(default='iteam_image.jpg', upload_to='iteam_images'),
        ),
    ]
