# Generated by Django 4.0.2 on 2022-04-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_shopiteam_iteam_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='udp',
            field=models.ImageField(blank=True, default='udpdefault.jpg', null=True, upload_to='udp_pics'),
        ),
    ]
