# Generated by Django 4.0.2 on 2022-04-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_shopiteam_date_time_shopiteam_iteam_catogories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='shop_pics',
            field=models.ImageField(blank=True, default='shop_pics/udpdefault.jpg', null=True, upload_to='shop_pics'),
        ),
    ]
