# Generated by Django 4.0.2 on 2022-04-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_shopprofile_shop_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_pics',
            field=models.ImageField(default='udpdefault.jpg', upload_to='shop_pics'),
        ),
    ]
