# Generated by Django 4.0.2 on 2022-05-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_shopprofile_shop_pics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopprofile',
            name='gender',
        ),
    ]
