# Generated by Django 4.0.2 on 2022-05-28 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_remove_shopprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shopprofile',
        ),
    ]
